### ISSUE TITLE
Add a stack trace to `NanoError`

### ISSUE THREAD

**Issue by binyamin** [alevroub/nano#1]
There's a V8 API which can capture the stack trace on errors. See [MDN on errors](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error#static_methods).

Example:
```js
export class CustomError extends TypeError {
	constructor(message, options) {
		super(message, options);
		this.name = 'CustomError';

		if (Error.captureStackTrace) {
			Error.captureStackTrace(this, CustomError);
		}
	}
}
```

Ref: https://github.com/alevroub/nano/blob/76081321e99295f63b179f60dfd7d50eb0540552/mod.ts#L25

**Comment by binyamin** [comment]
Note, that I haven't tested if this function works on Deno Deploy.

**Comment by alejandrovrojas** [comment]
As of `v1.0.0` the renderer uses the built-in `Error` object.

**Comment by binyamin** [comment]
@alevroub Now, how can I filter for errors which come from Nano? I liked the idea of a custom error object.

**Comment by alejandrovrojas** [comment]
So did I :~) I'll look into it.
